### PR TITLE
Implement token exchange strategy

### PR DESCRIPTION
**Pull request by krallin**
Basic implementation of [OAuth 2.0 Token Exchange](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-03#section-4.1).

### CODE REVIEW

**Comment by krallin** [comment]
cc @fancyremarker, looks like you might not actually be watching this particular repo!

**Comment by fancyremarker** [comment]
Thanks @krallin, merging. Part of me wants to get off of this forked oauth2 gem, so what are your thoughts on either:
- Pressing the upstream maintainers to accept this PR, #165, and #166, OR
- Removing the oauth2 dependency entirely from [token.rb in aptible-auth-ruby](https://github.com/fancyremarker/aptible-auth-ruby/blob/master/lib/aptible/auth/token.rb), as I mention in aptible/aptible-auth-ruby#7. I think this is the only place where we actually use the oauth2 gem anywhere.

**Comment by pboling** [comment]
@fancyremarker We have new maintainers (and a [whole new organization](https://github.com/oauth-xx)) around oauth2 gem now.  Please come back and give us your input re: the above. 🥂

**Comment by pboling** [comment]
Looking at this PR in particular, I would like to add this TokenExchange strategy to OAuth2.

CC @krallin

**Pull request merged**
